# Generated by Django 2.2 on 2019-04-10 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sprint', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('issue_date_created', models.DateTimeField(auto_now_add=True)),
                ('issue_date_modified', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bira.User')),
                ('project_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bira.Projectlist')),
            ],
        ),
    ]
