# Generated by Django 2.2 on 2019-04-10 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bira', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=50)),
                ('assignee', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sprint', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bira.Issue')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bira.User')),
            ],
        ),
    ]
