# Generated by Django 2.2 on 2019-04-10 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bira', '0004_auto_20190410_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.BooleanField(default=True),
        ),
    ]
